### ISSUE TITLE
Unable to add dependency in the project

### ISSUE THREAD

**Issue by abhinavtestbook** [afreakyelf/Pdf-Viewer#1]
I am unable to add the project dependency in app-level build.gradle whereas i am having jitpack in project level build.gradle
<img width="429" alt="Screenshot 2020-07-31 at 1 40 29 PM" src="https://user-images.githubusercontent.com/68221307/89014790-aef05400-d333-11ea-939d-2a500b64438e.png">

**Comment by afreakyelf** [comment]
Hi, Tag refers to latest version. For the latest version refer to readme file Jitpack badge. 
![image](https://user-images.githubusercontent.com/38572147/89015912-7cdff180-d335-11ea-8c21-3466e7cbca1f.jpeg)
