### ISSUE TITLE
[BUG] Pinch to Zoom offset 

### ISSUE THREAD

**Issue by heihitesh** [afreakyelf/Pdf-Viewer#106]
## 📝 Describe the Bug
When we perform, a pinch to zoom action in a pdf, It start to zoom in on a different position ( From top-left) 

## 📖 Library Version
    implementation "com.github.afreakyelf:Pdf-Viewer:2.0.5"

## 🚶 Steps to Reproduce
I am using this 
1) <com.rajat.pdfviewer.PdfRendererView
    android:id="@+id/pdfView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:pdfView_divider="@drawable/pdf_viewer_divider"
    app:pdfView_showDivider="false" />

2) Simply load a pdf from a File object.
3) Now do a "pinch to zoom" action, in the center. 
4) You will see instead of zooming the center, it would zoom the top-left corner of the pdf  

## 🤔 Expected Behavior
It should zoom the place where the action is performed 

## 🖼️ Screenshots/Videos
Can add, if the issue is not reproducible or unable to understand 

## 📱 Smartphone Info:
Android 13, Samsung 

---

**Comment by angad305** [comment]
Same issue here, the zoom in Android 13, Samsung - pinch to zoom is not proper.

**Comment by angad305** [comment]
https://github.com/afreakyelf/Pdf-Viewer/assets/34420642/b6876b87-2a4d-465c-beb5-5d1dc55d6bc7

Just to reproduce the issue, in the video i am zooming in the centre of the screen, but the zoomed part is the top left. thats the issue.

**Comment by angad305** [comment]
any update on the issue guys?

**Comment by afreakyelf** [comment]
Sorry for the delay. I am working on this now and should be able to release soon.

**Comment by afreakyelf** [comment]
Hi, Thanks for using the library. Please update your library to latest version. https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.7

Thanks!
