### ISSUE TITLE
How to import library locally for contribution?

### ISSUE THREAD

**Issue by mrgarciamanuel** [afreakyelf/Pdf-Viewer#110]
Hi, i'm new in this library and want to use it a projet, but i have some feature in mind that this library does not provide yet.

I just forked the repo and created my own branch, but i don't know how to use it locally in some projects.

From my resources, i think i have to generate .AAR/.JAR file of this library and import it in my project dependecies.

Can u please give some help.

Thank u for your attention.

**Comment by afreakyelf** [comment]
Sure! To use your forked library locally, follow these steps:

In your library module, generate the .AAR or .JAR file:

For Android Studio: Go to Build > Build Bundle(s) / APK(s) > Build APK(s) or Build AAR.
Alternatively, use Gradle commands like `./gradlew assembleRelease` for AAR.
Once generated, locate the .AAR or .JAR file in the build/outputs/ directory.

In your project, create a libs folder inside the app module if it doesn't already exist, and copy the .AAR or .JAR file there.

Add the file as a dependency in your project's build.gradle:

```gradle
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    // include other dependencies
}
```
Sync your project with Gradle files.

Now, your project should be able to use the local version of the library.
