### ISSUE TITLE
Publish library to mavenCentral

### ISSUE THREAD

**Issue by vanniktech** [afreakyelf/Pdf-Viewer#117]
Could you please publish the maven directly to maven central? That way no one has to rely on jitpack and it's the common practice for every library to be published to maven central.

**Comment by afreakyelf** [comment]
Hey @vanniktech, i reached out to you, i have been facing some issue while using your plugin. Please take a look at https://github.com/vanniktech/gradle-maven-publish-plugin/issues/749

**Comment by vanniktech** [comment]
Interesting, can you try again? Also I've automated the process in such a way that GitHub's Runner can do releases for me: https://github.com/vanniktech/blurhash/tree/master/.github/workflows - feel free to take those configs!

And then here https://github.com/afreakyelf/Pdf-Viewer/settings/secrets/actions you only need to create these 4 variables: 

<img width="793" alt="Screenshot 2024-03-28 at 09 26 20" src="https://github.com/afreakyelf/Pdf-Viewer/assets/5759366/1b8e5928-bd61-49d1-ba0d-1d96fbea66ff">

Release works by pushing a git tag. Snapshots are built automatically. You might need to tweak the branch names if you've got different ones.

**Comment by vanniktech** [comment]
Hmm what are the coordinates?
