### ISSUE TITLE
Pdf has been corrupted.

### ISSUE THREAD

**Issue by karishmapujara** [afreakyelf/Pdf-Viewer#12]
Hello

I am using PdfDocument to crerate PDF file. I am saving this file to app's Internal filesDir.
Now when I run below code I am getting "Pdf has been corrupted" Toast message

`startActivity(new PdfViewerActivity().Companion.launchPdfFromPath(Activity4.this, file.getAbsolutePath(), "", "", false));`

So what can I do?

Thank you

**Comment by afreakyelf** [comment]
Hi, Thanks for checking out the library.
 
This toast appears when pdf file is corrupted or Engine is failing to load.

I'd suggest you to check the file first please and then path and if both are correct and still not working. Send me the file and I will try to fix the bug.

Thank you 
Don't forget to ⭐️

**Comment by afreakyelf** [comment]
Huh strange. Just send me your pdf file here or @rjmittal07@gmail.com.
I will check it

**Comment by karishmapujara** [comment]
Here is the PDF file [AA.pdf](https://github.com/afreakyelf/Pdf-Viewer/files/5856345/AA.pdf)

**Comment by afreakyelf** [comment]
Hi @karishmapujara, Can you share your code with me (Github repo will work too). I want to see how the file system is picking after it downloads. 
Thank you

**Comment by karishmapujara** [comment]
Here is my code

File directory = new File(MainActivity4.this.getFilesDir() + File.separator + "MyFolder");
 File file = new File(directory, "/AA.pdf");
if (!directory.exists())
                directory.mkdir();

PrintAttributes printAttrs = new PrintAttributes.Builder().
                    setColorMode(PrintAttributes.COLOR_MODE_COLOR).
                    setMediaSize(PrintAttributes.MediaSize.ISO_A4).
                    setResolution(new PrintAttributes.Resolution("zooey", PRINT_SERVICE, 450, 700)).
                    setMinMargins(PrintAttributes.Margins.NO_MARGINS).
                    build();

PdfDocument myPdfDocument = new PrintedPdfDocument(this, printAttrs);
Paint myPaint = new Paint();

PdfDocument.PageInfo myPageInfo = new PdfDocument.PageInfo.Builder(595, 842, 1).create();
PdfDocument.Page myPage = myPdfDocument.startPage(myPageInfo);

Canvas canvas = myPage.getCanvas();

//photo
canvas.drawBitmap(scaledBitmap, 400, 100, myPaint);

//title
myPaint.setTextAlign(Paint.Align.CENTER);
myPaint.setTextSize(18f);
canvas.drawText("AA", myPageInfo.getPageWidth() / 2, yPos, myPaint);

myPdfDocument.finishPage(myPage);

myPdfDocument.writeTo(new FileOutputStream(file));

myPdfDocument.close();

startActivity(new PdfViewerActivity().Companion.launchPdfFromPath(MainActivity4.this, file.getAbsolutePath(), "a", "", false));`

**Comment by afreakyelf** [comment]
Hi @karishmapujara, Thank you for pointing out the issue. I have fixed it and released a new build. Kindly upgrade the version to v1.0.5.

Feel free to contribute to my library and star. 
Thank you.

**Comment by karishmapujara** [comment]
Now "Permission not granted" toast is showing.

I am saving the file in app's Internal Storage. So there is no need for any permission.

**Comment by afreakyelf** [comment]
Hi @karishmapujara , Please upgrade version to v1.0.6 and let me know. 

Thank you

**Comment by karishmapujara** [comment]
OK Done.
