### ISSUE TITLE
[BUG] set minSdk back to 21

### ISSUE THREAD

**Issue by vanniktech** [afreakyelf/Pdf-Viewer#120]
I've tried to upgrade to the latest 2.1.0 but it requires minSdk 24. Can it be lowered back to 21? This is also what AndroidX will set it to in the coming months. So we should support the same.

**Comment by afreakyelf** [comment]
Hi, this has been fixed in this new release. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.1.1

Thank you for using the library.

**Comment by vanniktech** [comment]
Amazing, thanks for the quick new release!
