### ISSUE TITLE
mistake in version number on maven central

### ISSUE THREAD

**Issue by asnav** [afreakyelf/Pdf-Viewer#121]
## 📝 Describe the Bug
the version on maven central is "v2.1.0" instead of "2.1.0"
(    implementation("io.github.afreakyelf:Pdf-Viewer:v2.1.0"    instead of        implementation("io.github.afreakyelf:Pdf-Viewer:2.1.0")    )

## 📖 Library Version
v2.1.0

**Comment by afreakyelf** [comment]
Hi, this has been fixed in this new release. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.1.1

Thank you for using the library.

**Comment by asnav** [comment]
great! tysm
