### ISSUE TITLE
Long click on text to start highlighting, for text copying

### ISSUE THREAD

**Issue by foodpoison** [afreakyelf/Pdf-Viewer#143]
**Is your feature request related to a problem? Please describe.**
Currently there doesn't seem to be a way for users to highlight texts in rendered PDF, would be good to enable this.

**Describe the solution you'd like**
Being able to select portions of text on screen, with standard gestures on text.

**Describe alternatives you've considered**
Doesn't look like there are any alternatives to text selection.

**Comment by afreakyelf** [comment]
Due to its capability of rendering PDFs in image format, selecting or highlighting them is impossible. We haven't explored the OCR yet. Thank you
