### ISSUE TITLE
[BUG] WRITE_EXTERNAL_STORAGE permission need maxSdkVersion="29"

### ISSUE THREAD

**Issue by lotosbin** [afreakyelf/Pdf-Viewer#148]
## 📝 Describe the Bug
Provide a clear and concise description of what the bug is.

## 📖 Library Version
- **PDF Viewer Version:** [e.g., 2.0.0]

## 🚶 Steps to Reproduce
Please follow these steps to reproduce the issue:
1. **Initial Setup/Library Method Used:** [e.g., `initWithUrl` method]
2. **Actions Taken:** [e.g., Clicked on 'Load PDF']
3. **Unexpected Behavior:** [e.g., PDF not loading]
4. **Relevant Code/Stack Trace:** [Include code snippet or stack trace if applicable]

## 🤔 Expected Behavior
What did you expect to happen?

## 🖼️ Screenshots/Videos
If applicable, add screenshots or videos to help explain your problem.

## 📱 Smartphone Info:
- **Device:** [e.g., Samsung Galaxy S10]
- **OS:** [e.g., Android 11]
- **Library Version:** [e.g., 2.0.0]

## 💻 Code Snippets
Include relevant code snippets or links to code repositories.

## 📜 Log Output/Stack Trace
Include any error logs or stack trace for more context.

## 💬 Additional Context
Add any other context about the problem here. Mention if the issue is consistent, specific scenarios where the bug occurs, etc.

---

**Comment by afreakyelf** [comment]
Please provide/add more detail to actual issue. Closing it for now, feel free to reopen.
