### ISSUE TITLE
Remove <uses-permission> and requestLegacyExternalStorage config from library manifest

### ISSUE THREAD

**Issue by BenTilbrook** [afreakyelf/Pdf-Viewer#17]
The library `AndroidManifest` includes various permissions that the consuming app potentially does not need. These include:

* `requestLegacyExternalStorage`
* `READ_PHONE_STATE`
* `ACCESS_MEDIA_LOCATION`

and others.

The library should not declare any of these permissions, nor `requestLegacyExternalStorage`, and instead make it the responsibility of the consuming app to declare what it needs.

**Comment by kklolo** [comment]
I totally agree please fix this as scoped storage for android 11 is introduced and requestLegacyExternalStorage is no longer avilible.

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
