### ISSUE TITLE
Page index is not updating correctly

### ISSUE THREAD

**Issue by DanDayne** [afreakyelf/Pdf-Viewer#18]
**Describe the bug**
When scrolling, the index of the page is not updating correctly. I've noticed it gets stuck especially when working with large PDFs.

**To Reproduce**
1. Open a multi-page PDF
2. Scroll
3. Observe the page counter

**Screenshots**

https://user-images.githubusercontent.com/47151975/116997067-98b95f00-acdc-11eb-98af-088fc84962bc.mp4

**Smartphone (please complete the following information):**
 - Device: [Nexus 10 (emulator)]
 - OS: [Android API 29]
 - Application version 1.0.7

**Comment by shivanshuraj** [comment]
Yes, that's true. Page index doesn't work correctly.

**Comment by sooshil** [comment]
this happened for me as well. 
While scrolling, the page scrolling stuck for a while on second page. After keep trying to scroll, the page scrolls but the page number stuck on 2.

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
