### ISSUE TITLE
Add a loading indicator if the PDF is not ready to be read

### ISSUE THREAD

**Issue by DanDayne** [afreakyelf/Pdf-Viewer#19]
**Describe the bug**
Large PDFs are not fully loaded for the first few seconds after opening the activity. Only the first page or two are shown, the rest are rendered later. This period extends with the increasing size of PDF it is tested with. 

**To Reproduce**
1. Open a large PDF
2. Try to scroll down

**Expected behavior**
I understand that the PDF needs to be loaded first. I would expect a loading circle of some sort while the PDF is not fully displayed as an indicator that the PDF is not yet ready to be read. 

**Screenshots**

https://user-images.githubusercontent.com/47151975/116998175-1c278000-acde-11eb-9fd1-fa6c7263505d.mp4

**Smartphone:**
Device: [Nexus 10 (emulator)]
OS: [Android API 29]
Application version 1.0.7

**Comment by AlirezaIvaz** [comment]
Same issue in S10e Android API 29

**Comment by umer-sufyan** [comment]
Yes issue with large pdf still exist

**Comment by ArboledaAS** [comment]
how it is implemented I do not understand very well how it is done

**Comment by sagarbandamwar** [comment]
@afreakyelf how to add loading indicator? while loading PDF
@DanDayne any luck how to add loading indicator / Progress Dialog while loading

**Comment by afreakyelf** [comment]
Hi, there is a flag which can be set to true to enable progress bar while pages are loading in theme.
`    <item name="pdfView_enableLoadingForPages">true</item>
`
