### ISSUE TITLE
App crash when minimise and reopen app.

### ISSUE THREAD

**Issue by vicky-droid** [afreakyelf/Pdf-Viewer#2]
**App crashed**
`Fatal Exception: java.lang.RuntimeException: Unable to stop activity {com.letzconnect/com.rajat.pdfviewer.PdfViewerActivity}: java.lang.IllegalStateException: Already closed
`
**To Reproduce**
1. open PdfViewerActivity
2. minimize the app
3. Reopen the app from the minimized tray or from the launcher icon.
4. the app will get crashed

**Cause**
`onStop()
binding.pdfView.closePdfREnder()
`
if you cant reproduce the case ping me.

**Comment by afreakyelf** [comment]
Hey @vicky-droid , Thanks for tracking the issue. I will try to resolve this by the weekend (got office load this week).
Sure, You can also try. Contributions are always appreciated.
