### ISSUE TITLE
Possible with JSON items?

### ISSUE THREAD

**Issue by DrewStephensCoding** [afreakyelf/Pdf-Viewer#20]
I'm working on an app that has pdf urls in a json response, but the library doesn't seem to work with those.  Do you possibly have a potential workaround and use for this?

**Comment by afreakyelf** [comment]
Can you put your JSON here and how you are trying to use URLs please let me know.

**Comment by DrewStephensCoding** [comment]
Apologies, I got it working correctly! I guess I had something wrong
