### ISSUE TITLE
AAPT: warn: multiple substitutions specified in non-positional format;

### ISSUE THREAD

**Issue by YuanWenHai** [afreakyelf/Pdf-Viewer#21]
**Describe the bug**
When I import this into my project,the gradle compiler will show  **Android resource compilation failed**  and compile filed.
like that:
![微信截图_20210628113550](https://user-images.githubusercontent.com/16665664/123584294-b1914d00-d813-11eb-9c11-d22fa8b5268c.png)

If I remove this lib,everything is ok.

**Comment by afreakyelf** [comment]
Hi, Have you tried recent version of this library? This above issue normally occurs when there is a conflict between the resources.
