### ISSUE TITLE
Pinch zoom feature request

### ISSUE THREAD

**Issue by ugurcany** [afreakyelf/Pdf-Viewer#22]
**Is your feature request related to a problem? Please describe.**
I'm currently using `PdfRendererView` in my project. I want to add pinch-to-zoom functionality to it.

**Describe the solution you'd like**
I would like to enable this feature with a boolean flag, such as:
`pdfRenderView.isPinchZoomEnabled = true
`

**Describe alternatives you've considered**
Not possible currently.

**Comment by ugurcany** [comment]
Closing since this feature is existing, but couldn't perform pinch zoom on an emulator. Seems like only possible on real device.

**Comment by afreakyelf** [comment]
You can perform pinch and zoom by pressing control and dragging the cursor on Emulator.

Thank you for checking out the library. 

🙌🏻
