### ISSUE TITLE
Changing Page Index Indicator Style/Text

### ISSUE THREAD

**Issue by ugurcany** [afreakyelf/Pdf-Viewer#23]
**Is your feature request related to a problem? Please describe.**
We are using `PdfRendererView` in our project in production. I need to change page indicator text (see below) as our app is released in a foreign market where people cannot speak English.
![image](https://user-images.githubusercontent.com/9681668/124178121-d7d81680-dab9-11eb-8d19-beda785c16d4.png)

**Describe the solution you'd like**
As a first step, maybe styling is not that much important, but the text itself is. At least, I would like to be able to make it something like "6 / 17". 

**Describe alternatives you've considered**
No alternative is acceptable currently, because non-English speakers may not understand "of" in between of page index and total page count.

**Comment by afreakyelf** [comment]
Sure, I get your point. Let me see what can I do. I will try few options and will update you.

**Comment by chihung93** [comment]
@ugurcany :
I have created 2 PRs for that:

1. https://github.com/afreakyelf/Pdf-Viewer/pull/47
2. https://github.com/afreakyelf/Pdf-Viewer/pull/48


Please help me to review and merge it @afreakyelf
