### ISSUE TITLE
Get PDF URL From Protected Link

### ISSUE THREAD

**Issue by Emefar** [afreakyelf/Pdf-Viewer#29]
I need send header parameter for get pdf from url. I'm normally sending 'cookie' header value when i get image or pdf file. Can you develop add header feature for get pdf from url?

**Comment by afreakyelf** [comment]
Sure i will give it a try.

**Comment by amit517** [comment]
Hey, I have added that auth header on top of your library. I have added your library locally and done some modifications. If you are available I can push those codes maybe.

**Comment by Emefar** [comment]
Yes I'm available for testings, please commit latest codes to new branch

**Comment by Emefar** [comment]
@amit517 Do you have any sample for protected link? I need send auth to header. I need send "auth", "authentication" or any header with value

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
