### ISSUE TITLE
Showing pdf as a view 

### ISSUE THREAD

**Issue by javadghane** [afreakyelf/Pdf-Viewer#30]
This would be great if  PDF viewer be a view not a external activity.

**Comment by afreakyelf** [comment]
I will try to do that. But it can limit functionalities.
Feel free to contribute if you can.

**Comment by umer-sufyan** [comment]
I think PdfRendererView does the job. 
Sample usage could be as follow

in xml some where on screen 

<com.rajat.pdfviewer.PdfRendererView
        android:id="@+id/pdfView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/play"
        android:layout_below="@+id/tv_header"
        android:layout_marginHorizontal="5dp"
        android:layout_marginBottom="5dp"
        android:background="@android:color/transparent"
        android:clickable="true"
        android:contextClickable="true" />

In Activity
 PdfRendererView pdfView;

oncreateActivity
 pdfView = (PdfRendererView) findViewById(R.id.pdfView);

and to open it with
pdfView.initWithPath(assetFileName, PdfQuality.ENHANCED);

this works fine, the problem that I am facing is with quick scrolling it just stop loading large pdf.

**Comment by afreakyelf** [comment]
Hi, It can be used as view. You can cherry pick files and implement. I did not provide that flexibility yet because the purpose is to make it easier to support other functionalities such as download etc. In future, if requirement arise, I will try to add.
