### ISSUE TITLE
Allow download from HTTP website

### ISSUE THREAD

**Issue by ghost** [afreakyelf/Pdf-Viewer#36]
Hello,
thanks for your library.
Currently only HTTPS connections are allowed.
Could you add the possibility to get PDF from HTTP connection.

`Cleartext HTTP traffic to ... not permitted`

You could put an option to the current call:
```
fun launchPdfFromUrl(
            context: Context?,
            clearText: Boolean = false, //allow clear text (HTTP) connection
            pdfUrl: String?,
            pdfTitle: String?,
            directoryName: String?,
            enableDownload: Boolean = true
        )
```

**Comment by afreakyelf** [comment]
Hi, Allowing from insecure HTTP connection is not a good practice that is why i can not declare it for all. However please feel free to checkout the repo and take the code of library and change the manifest file. 

Then you can try in your application - 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```
