### ISSUE TITLE
Allow messages customization

### ISSUE THREAD

**Issue by ghost** [afreakyelf/Pdf-Viewer#37]
I've notice that the activity PdfViewerActivity.kt has some toast messages with build in strings.
Could you please move all the embedded text (PdfViewerActivity.kt and other classes) in the string resource file?
In that case I could translate in italian language ^^ and other ppl can provide their own translations.

Thanks for your support.

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
