### ISSUE TITLE
Can I convert a pdf Page with this?

### ISSUE THREAD

**Issue by mrabhinv** [afreakyelf/Pdf-Viewer#38]
**Is your feature request related to a problem? Please describe.**
I want to convert a single pdf page into an image

**Describe the solution you'd like**
with android-pdfview and derivatives you could do something like this https://stackoverflow.com/questions/10698360/how-to-convert-a-pdf-page-to-an-image-in-android

**Describe alternatives you've considered**
android-pdfview of course but its huge

**Comment by afreakyelf** [comment]
You can go inside my code and take the code reference where each page is being converted into a bitmap and use that.
