### ISSUE TITLE
Give the PdfRenderView item a default height

### ISSUE THREAD

**Issue by Loong-T** [afreakyelf/Pdf-Viewer#41]
Thanks for your nice work.
English is not my first language, I will try my best to describe my problem.

I implemented my own PdfViewerActivity by using PdfRendererView.
After opening a big pdf file, like more than 200 pages, the render core will try to build the bitmap all of the pages.
This is because that the height of the recycler view item is *wrap_content*, which means 0 pixel. So the recycler view will try to load as more items as possible which seems like "block" the rendering.
And, buildBitmap runs in a GlobalScope, the jobs won't be canceled when activity is destroyed. After close the large pdf and try to open a small pdf file, the rendering is still blocked since there are still lots of jobs remaining.

I think this can be fixed by giving list item a default height, such as 480dp, so that the recycler view won't request a lots of buildBitmap jobs.

**Comment by afreakyelf** [comment]
Thank you for the suggestion. I will give it a try.
If you have time and are familiar with kotlin, Please feel free to fork and contribute.
