### ISSUE TITLE
Read Pdf From Remote URL With JAVA

### ISSUE THREAD

**Issue by karim-eg** [afreakyelf/Pdf-Viewer#43]
**Load pdf from url online with java not in assets**
i have a pdf library saved in database online and i want users read these books online "preview" not from assets,
Can U Add it please

**Comment by afreakyelf** [comment]
in case of Java, to call "launchPdfFromUrl" method you need to use
PdfViewerActivity.companion.launchPdfFromUrl because library is written in kotlin.
Hope that helps.
