### ISSUE TITLE
Why it takes so much time to load Pdf  and its did not loads properly when we are having more pages in Pdf?

### ISSUE THREAD

**Issue by RahulRaviandroid** [afreakyelf/Pdf-Viewer#44]
When there are more than 10 pages in a Pdf File then it takes so much time to load and its did not loads pages properly when we are having more pages in Pdf

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
