### ISSUE TITLE
On clicking the Pdf twice it should Zoom

### ISSUE THREAD

**Issue by RahulRaviandroid** [afreakyelf/Pdf-Viewer#45]
currently zoom functionality is only for pinch, but zoom is not for double touch on Pdf

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
