### ISSUE TITLE
PdfViewerActivity Error

### ISSUE THREAD

**Issue by mukul2428** [afreakyelf/Pdf-Viewer#5]
Using this in java and i am unable to get PdfViewerActivity, as it is showing not found error...(Dependency Added)

**Comment by afreakyelf** [comment]
Hi Mukul, Thanks for checking out the repo.
I am sure if you have added the dependency currently, you will be able to import PdfViewerActivity. 
But in case of Java, to call "buildIntent" method you need to use
_PdfViewerActivity.companion_.

Please check the dependency and implementation again and let me know.

**Comment by mukul2428** [comment]
Can you please send whole implementation in java? How to use this library
in java?

**Comment by afreakyelf** [comment]
Hi Please try this way.

```
implementation 'com.github.afreakyelf:Pdf-Viewer:1.0.3'
```

```
launch_pdf.setOnClickListener(v -> {
        startActivity(
                PdfViewerActivity.Companion.buildIntent(
                        this,
                        "pdf_url",                                // PDF URL in String format
                        false,
                        "Pdf title/name ",                        // PDF Name/Title in String format
                        "pdf directory to save",                  // If nothing specific, Put "" it will save to Downloads
                        false                    // This param is true by defualt.
                )
        )
  });
```

**Comment by mukul2428** [comment]
Thanks brother, it worked... please one more request..how can i save my pdf
file in cache memory because i need to open that file again and again and
it takes lot of time and internet for opening.

**Comment by afreakyelf** [comment]
Saving file into cache is still in pending. Feel free to modify if you can and raise PR or else I will add by evening.

Don't forget to ⭐️ repo.

Thanks
