### ISSUE TITLE
Jitpack version 1.0.8 is empty (v1.0.8 works).

### ISSUE THREAD

**Issue by DanielNovak** [afreakyelf/Pdf-Viewer#52]
The 1.0.8 release on Jitpack is empty / NotFound:
https://jitpack.io/com/github/afreakyelf/Pdf-Viewer/1.0.8/
but the version name with a `v` prefix works:
https://jitpack.io/com/github/afreakyelf/Pdf-Viewer/v1.0.8/

**Comment by emartynov** [comment]
Looks like the same happened with 1.0.0 :-(
