### ISSUE TITLE
PDF has been corrupted

### ISSUE THREAD

**Issue by surajdevelops** [afreakyelf/Pdf-Viewer#53]
When I am using the v1.0.1 it's throwing the error `PDF has been corrupted` but when I am downgrading it to v1.0.6 then it's working fine.

Kindly revert any changes if you have done in v1.0.1 which might be causing the aformentioned error.

**Comment by surajdevelops** [comment]
I checked it, it is working even in just one decrement version i.e `v1.1.0` but not working on 'v1.1.1'

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
