### ISSUE TITLE
Double Tap to Zoom

### ISSUE THREAD

**Issue by surajdevelops** [afreakyelf/Pdf-Viewer#54]
Please add the **Double Tap to Zoom** feature, right now user's are not aware the PDF can be zoomed or not, some users don't explicitly try to **Pinch to Zoom**  and leave it thinking the PDF can not be zoomed. It'll be great if Double Tap to Zoom can be by default.

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
