### ISSUE TITLE
ic_arrow_back.xml overrides project's icon

### ISSUE THREAD

**Issue by oleksandr-koba-hhl** [afreakyelf/Pdf-Viewer#55]
Please rename or delete the icon in the `anydpi` folder because it overrides the project's icon with the same name.
Thank you.

![image](https://user-images.githubusercontent.com/103187497/207809423-51029598-a8de-4afb-9c74-a14f97e5c88e.png)

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
