### ISSUE TITLE
Version 1.1.1 requires multidex

### ISSUE THREAD

**Issue by oleksandr-koba-hhl** [afreakyelf/Pdf-Viewer#56]
After the update from 1.1.0 to 1.1.1, the library suddenly started to require a Multidex library.

![image](https://user-images.githubusercontent.com/103187497/207810197-ee558f03-fd14-4546-803b-b5ba3e1cd1c8.png)

**Comment by mcanyucel** [comment]
You can add `android.enableJetifier=true` in gradle.properties to solve the error. It will result in increased compile times, though.
