### ISSUE TITLE
Files are downloading very let after downlaod button click

### ISSUE THREAD

**Issue by rakibesachin166** [afreakyelf/Pdf-Viewer#58]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samsadch** [comment]
Can you check your internet connectivity?

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
