### ISSUE TITLE
Scroll state is not retained

### ISSUE THREAD

**Issue by samsadch** [afreakyelf/Pdf-Viewer#64]
**Describe the bug**

**To Reproduce**
1. Go to 'Home'
2. Click on 'Open pdf'
3. Scroll down to 'any page'
4. Rotate the screen
5. See error which is the scroll state is not retained and scrolling to the initial state

**Expected behavior**
While rotating the screen if the user scrolled down from first page to any other page expected to retain the page on rotation event.

**Smartphone (please complete the following information):**
 - Device: Samsung s10 Lite
 - OS: Android

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
