### ISSUE TITLE
Download feature doesn't work on Android 11 and up

### ISSUE THREAD

**Issue by AlexDiak** [afreakyelf/Pdf-Viewer#70]
I've tested in a real device with AOSP Android 11 and in emulator with Android 13 and the download button does nothing. I have also tested it in Android 9 and it seems to work fine.

**Comment by fadhyyusuf** [comment]
Im facing the same issue.

**Comment by lambui09** [comment]
same issue on android 13

**Comment by ApunichGULSHER** [comment]
Same problem

**Comment by ApunichGULSHER** [comment]
@AlexDiak @fadhyyusuf @lambui09 
Remove storage permission for target API 33, Android 13 and lower Android version devices don't requires READ or WRITE external storage permissions to save PDF in download folder.
 I had downloaded this repo and imported as module in my android project, than removed all storage related permissions. Downloading PDF working like charm in Android 13 as well as lower versions now.

**Comment by PeterWagih90** [comment]
@ApunichGULSHER Can you please contact me through mail, regarding this issue i need the build stripped from premission ASAP

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
