### ISSUE TITLE
pdf文件很大的时候比如一个119页的pdf滚动到最后面时 加载数据错乱，频繁刷新

### ISSUE THREAD

**Issue by Victor2018** [afreakyelf/Pdf-Viewer#79]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by afreakyelf** [comment]
Closing as the issue is not clear.
