### ISSUE TITLE
[BUG] Not able to download the latest version of this lib

### ISSUE THREAD

**Issue by hiteshsarsava** [afreakyelf/Pdf-Viewer#89]
## 📖 Library Version
- **PDF Viewer Version:** 2.0.1
---
![image](https://github.com/afreakyelf/Pdf-Viewer/assets/16486943/85db7000-ae1a-4d13-92f5-c3ab5f32ff51)

**Comment by afreakyelf** [comment]
Hey, would you mind sharing how are you implementing the dependency? And what is your gradle version?

**Comment by afreakyelf** [comment]
Hi, I have fixed the issue in new tag https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.2 .  Thank you for using this library.

Please use : `implementation("com.github.afreakyelf:Pdf-Viewer:v2.0.2")`
