### ISSUE TITLE
[BUG] Jetpack Compose view has zero width

### ISSUE THREAD

**Issue by kevinvanmierlo** [afreakyelf/Pdf-Viewer#96]
## 📝 Describe the Bug
Exactly what the title says. The view has zero width in Jetpack Compose. So I can't see the PDF right now

## 📖 Library Version
- **PDF Viewer Version:** 2.0.4

## 🚶 Steps to Reproduce
Please follow these steps to reproduce the issue:
1. Use Jetpack Compose
2. Add a Column with modifier fillMaxSize, inside add a TopAppBar and a Box with fillMaxSize. Inside this Box set the PdfRendererViewCompose.

## 🤔 Expected Behavior
To see the PDF. If you could provide the modifier I could give it a width and height myself and this issue would be fixed.

---

**Comment by afreakyelf** [comment]
Hi This bug has been fixed in this build. https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.5

Thank you!
