### ISSUE TITLE
Project using Pdf-Viewer (AFI Explorer) 

### ISSUE THREAD

**Issue by drewstephensdesigns** [afreakyelf/Pdf-Viewer#99]
Howdy! Just want to say thank you for making an awesome, lightweight library.

My project [AFI Explorer](https://github.com/drewstephensdesigns/AFIExplorer) uses this project as a fall back.  The app is geared towards Air Force personnel for an easy way to navigate all of our publications and references.

Thank you again!

Drew

**Comment by afreakyelf** [comment]
Thank you so much for the kind words. Means alot!!!
